### PR TITLE
Closes #36

### LINKED ISSUE #36: !song close/open does not provide confirmation response
Performing `!song close` or `!song open` commands does not provide the user with a confirmation that the song queue has closed/opened. This may cause concern that the bot may be broken and/or the command did not register.

### PR DESCRIPTION
**Pull request by Jqnxyz**

### CODE REVIEW

File: bot/src/module/song.rs [hunk 1]
```diff
@@ -258,10 +258,12 @@ impl command::Handler for Handler {
                     "" => None,
                     other => Some(other.to_string()),
                 });
+                ctx.user.as_owned_user().respond("Closed player from further requests.");
```
Comment (udoprog) [inline bot/src/module/song.rs]: `ctx.respond(...)` should be a shorthand which doesn't require taking ownership for this.

File: bot/src/module/song.rs [hunk 2]
```diff
@@ -258,10 +258,12 @@ impl command::Handler for Handler {
...
             }
             Some("open") => {
                 ctx.check_moderator()?;
                 self.player.open();
+                ctx.user.as_owned_user().respond("Opened player for requests.");
```
Comment (udoprog) [inline bot/src/module/song.rs]: Same here.

**Comment by udoprog** [comment]
I think you can rebase to get rid of the merge commits above (`git rebase origin/master`).
